apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bu4e
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0022-tenant/tkrw-pr714-0075-0022-app/devfile-sample-bu4e@sha256:d9662fba82822c4a22881c678f1d38fff1ed63a6dc1c7e1c41a7768d141c7518
        name: my-nodejs
        resources: {}
status: {}
